# Generated by Django 6.1 on 2026-09-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('item_desc', models.CharField(max_length=850)),
                ('item_price', models.DecimalField()),
                ('item_image', models.CharField(default='https://tse2.mm.bing.net/th/id/OIP.7OYh9Zt5JGrlaCVgiRz17AHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3', max_length=500)),
            ],
        ),
    ]
