# Generated by Django 6.1 on 2026-08-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_items_item_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
