# Generated by Django 6.1 on 2026-09-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://tse2.mm.bing.net/th/id/OIP.7OYh9Zt5JGrlaCVgiRz17AHaE8?r=0&rs=1&pid=ImgDetMain&o=7&rm=3', max_length=500),
        ),
    ]
