# Generated by Django 6.1 on 2026-09-12 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_delete_category_item_created_at_item_is_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_name', 'item_price'], name='food_item_item_na_21352b_idx'),
        ),
    ]
